name: Format Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  black:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: application
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - run: pip install -r requirements.txt

      - name: Run Format Check with Black
        run: black --check .

  prettier:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: application
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run Format Check with Prettier for HTML, CSS, and JS
        run: npx prettier "**/*.{html,css,js}" --check
