name: Run Unittests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unittest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: application

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest
